global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gradio_app'
    static_configs:
      - targets: ['localhost:8000']  # Gradio metrics

  - job_name: 'node_exporter_gradio'
    static_configs:
      - targets: ['localhost:9100']  # Node Exporter

  - job_name: 'textgenpro_metrics'
    static_configs:
      - targets: ['localhost:11112']  # Metrics from TextGenPro container
